### PR TITLE
Submission to ICLR 2023 Blogposts Track

### PR DESCRIPTION
**Pull request by sudo-Boris**
This is our submission to the Blogpost Track.

Nevertheless, we seem to have an issue with the citations and would love to ask for assistance in resolving the issue.

### CODE REVIEW

**Comment by busycalibrating** [comment]
Sure! What issues are you facing?

**Comment by sudo-Boris** [comment]
> Sure! What issues are you facing?

Great, thank you very much!
For some reason, our citations are not appearing in the main text and we don’t have an automatically generated references appendix. I‘m not sure why, because I just used the template of the example blog post.

**Comment by busycalibrating** [comment]
Ok I think I figured it out. It seems to be a problem with your description; I was able to make things work by:
- removing any quotes (both double and single) in the description
- removing any citations in the description
- removing any hrefs (or any html really) in the description.

With that, it seems to be working:

**Comment by sudo-Boris** [comment]
Okay, I removed the quotes and reduced the size of the large video. That's interesting, that even the quotes led to issues!

Regarding the rendering issue, I hope the smaller size fixes it in your case because everything renders OK when I host the blog locally.

**Comment by busycalibrating** [comment]
Sounds great - I'll merge it in and we'll see if it works! If not we'll try to diagnose it afterward.

**Comment by busycalibrating** [comment]
Hmm unfortunately it seems like they don't render: 

https://iclr-blogposts.github.io/staging/blog/2023/Adaptive-Reward-Penalty-in-Safe-Reinforcement-Learning/

I'm not sure what the issue is here but could you possibly test locally on a linux device?

**Comment by sudo-Boris** [comment]
Hmm weird, for me, everything renders when I click on the link! I'm running on MacOS Monterey.

**Comment by busycalibrating** [comment]
@sudo-Boris 

I think I figured out a workaround that should work - could you refer to my response in #17? I'll admit it's not ideal (I'll see if I can figure out how to incorporate videos into the `figure` html env), but for now this renders locally for me so I expect this to work on github pages.

Note that I did revert the merge so you'll need to open a new PR - when you do, could you also undo the changes to the docker-compose and template `.bib` file? Thanks a lot!

**Comment by sudo-Boris** [comment]
Okay, I will change the code of including videos in the blog as you have mentioned in #17, I will undo the changes to the docker-compose and template `.bib` file, and I will open a new PR.

**Comment by sudo-Boris** [comment]
No worries, everything seems to work out in the end, and that is what counts :)
(Just to mention, the <figcation> text appears in black even when the blog is set to dark mode and is pretty hard to read. At least in my local render).

**Pull request merged**
