### PR TITLE
ICLR Blog Post Submission

### PR DESCRIPTION
**Pull request by rajatsahay**
ICLR Blogpost Submission

### CODE REVIEW

**Comment by rajatsahay** [comment]
All done! Please merge if no changes are required. Thanks.

**Comment by rajatsahay** [comment]
Are there any changes to be made @busycalibrating ? I see a WIP label but no comments. If not, please merge.

**Comment by busycalibrating** [comment]
I did leave a few comments that you should be able to see regarding the "front matter" of your post

**Comment by rajatsahay** [comment]
Hey @busycalibrating I honestly do not see any comments in the entire thread apart from my own. I'm not sure what's up. 
Screenshot 2023-02-13 at 9 07 56 PM

Can you comment again? Or maybe drop me an email at rajatsahay.vit@gmail.com

**Comment by busycalibrating** [comment]
Sorry that was my fault! I forgot to submit the review :facepalm:

**Comment by rajatsahay** [comment]
No issues. It's done. I hope everything is fine now.

**Pull request merged**
