### PR TITLE
A Match Made in Drug Discovery: Marrying Geometric and Diffusion Models

### PR DESCRIPTION
**Pull request by arunraja-hub**
Hi @busycalibrating,
We have been given an extension till today by Professor Gidel. So we are making our submission. 
We have decided to change our blogpost title to "A Match Made in Drug Discovery: Marrying Geometric and Diffusion Models"
My teammate @MeilinaR had opened a PR earlier (https://github.com/iclr-blogposts/staging/pull/7) but there were some issues with rebasing it so we have opened this new PR. 

Could you please help to check if the markdown is being rendered without any issues on your side? We are having some technical issues with Jekyll.
Please let us know if there are any issues and we will resolve it
Thank you very much!

### CODE REVIEW

**Comment by busycalibrating** [comment]
I've fixed the front matter and it looks good on my end - feel free to double check it before I merge it in

**Comment by arunraja-hub** [comment]
Thank you! Are you able to view the images?

**Comment by busycalibrating** [comment]
Yep! Some math/latex stuff looks off though:

image

image

**Comment by MeilinaR** [comment]
Think I should have fixed the formatting issues above! Were there any other issues? (I unfortunately am having some trouble getting Jekyll to run properly, as I did notice that on MacOS Ventura there were some dependency problems.)

**Comment by busycalibrating** [comment]
Looks good! Thank you for the submission, I merged it in now

**Comment by MeilinaR** [comment]
Hi, tiny correction! I did see the following, and that there were some troubles rendering some multi-author citations like in the second picture:

load1


load

What would be the best way to fix it? Sorry for the hassle, as I could not render the blogpost locally!

**Comment by MeilinaR** [comment]
Additionally, we wanted to update the title on OpenReview as the submission still had our old title -- however, when trying to change it we saw that the invitation had expired. Do you know if we could fix this, or leave it with our old title?

**Comment by MeilinaR** [comment]
@busycalibrating would you mind helping us out again?

**Comment by busycalibrating** [comment]
I've pushed some fixes to the above issues with blogpost! Re: OpenReview I'll ask my colleague about this, but I think it should be fine with the old title worst case scenario.

**Pull request merged**
