### PR TITLE
Submission of Abstract of Blog post

### PR DESCRIPTION
**Pull request by Hstellar**

### CODE REVIEW

**Comment by busycalibrating** [comment]
Can you undo the changes you made to the original template files?

**Comment by busycalibrating** [comment]
Please let me know when this is ready to be merged!

**Comment by Hstellar** [comment]
I created a pull request with update conflict. Sorry for delay in answering.

**Comment by Hstellar** [comment]
Hi, on my fork it still shows Process completed with exit code 128 on deploy. Is it the same issue with new pull request as well? If so, can you tell me which files I might have changed.

**Comment by busycalibrating** [comment]
https://iclr-blogposts.github.io/staging/blog/2023/controllable-music-generation-via-midi-ddsp/ It looks ok on my end - does this look like you intended?

**Comment by Hstellar** [comment]
Hi, yes. Thank you!

**Pull request closed without merging**
